/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.kite9.java-conventions")
    kotlin("multiplatform") version "1.8.10"
}

dependencies {
    api("org.jetbrains.kotlin:kotlin-stdlib:1.8.10")
}

kotlin {
    jvm()
}

description = "Kite9 Visualization Common"
