/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.kite9.java-conventions")
    kotlin("multiplatform") version "1.8.10"
}

dependencies {
    api(project(":kite9-visualization-common"))
    api("org.xmlunit:xmlunit-core:2.9.0")
    api("org.jetbrains.kotlin:kotlin-stdlib:1.8.10")
    api("com.fasterxml.jackson.core:jackson-annotations:2.13.3")
}


kotlin {
    jvm()
}

description = "Kite9 Pipeline Common"
