package org.kite9.diagram.batik.format;

import org.apache.batik.svggen.DefaultErrorHandler;
import org.apache.batik.svggen.DefaultImageHandler;
import org.apache.batik.svggen.DefaultStyleHandler;
import org.apache.batik.svggen.SVGGeneratorContext;
import org.apache.batik.svggen.SVGIDGenerator;
import org.w3c.dom.Document;

public class ExtendedSVGGeneratorContext extends SVGGeneratorContext {
	
	public ExtendedSVGGeneratorContext(Document domFactory) {
		super(domFactory);
	}
	
	/**
	 * Helper method to create an <code>SVGGeneratorContext</code> from the
	 * constructor parameters.
	 */
	public static ExtendedSVGGeneratorContext buildSVGGeneratorContext(Document domFactory) {
		ExtendedSVGGeneratorContext generatorCtx = new ExtendedSVGGeneratorContext(domFactory);
		generatorCtx.setIDGenerator(new SVGIDGenerator());
		generatorCtx.setExtensionHandler(new BatikPaintExtensionHandler());
		generatorCtx.setStyleHandler(new DefaultStyleHandler());
		generatorCtx.setImageHandler(new DefaultImageHandler());
		generatorCtx.setComment("Generated by the Batik Graphics2D SVG Generator and Kite9");
		generatorCtx.setErrorHandler(new DefaultErrorHandler());
		return generatorCtx;
	}
}
